export const DELETE_QUERY = 'deleteQuery'
export const EXECUTE_PAGINATED_SELECT = 'executePaginatedSelect'
export const EXECUTE_SELECT = 'executeSelect'
export const FETCH_QUERY = 'fetchQuery'
export const SAVE_QUERY = 'saveQuery'
